### ISSUE TITLE
Chyba testování funkce substr

### ISSUE THREAD

**Issue by janfitz** [H00N24/ifj_tester#6]
U testování chybových kódů vracených funkcí substr testy očekávají indexování znaků řetězce od jedničky. Dle zadání je to od nuly. Konkrétně jsou to testy: exec_test3 a exec_test5

**Comment by edcuba** [comment]
@H00N24

**Comment by NoName115** [comment]
@janfitz 
Obidva testy sú mimo vstupných hodnôt v okrajových hodnotách kde mame implementovať správanie funkcie z jazyku Java. Testy aj tak očakávajú chybu. Ak si pozrieš súbor .out tak je prázdny test očakáva chybu.
