### ISSUE TITLE
exec_test_2.code, exec_test_44.code

### ISSUE THREAD

**Issue by Zippersk** [H00N24/ifj_tester#7]
Testy v podstate rovnaké. V oboch sa vracia hodnota vo void funkciach. Prečo jeden vracia chybu 8 a druhý 4?

 **exec_test_2.code:**
```
class Main
{
    static void run()
    {
        double v = voidFunction(2.589);
    }

    static void voidFunction(double d)
    {
        return 12.58;
    }
}
```
vracia 8

**exec_test_44.code**
```
class Main
{
	static void run()
	{
		test();
	}

	static void test()
	{
		return 5;
	}
}
```
vracia 4

**Comment by NoName115** [comment]
@Zippersk
Funkcie niesu totožné keďže v prvej nastane chyba priradenie hodnoty do premennej z void funkcie co je chyba 8. V druhej je iba návrat hodnoty z funkcia void co je chyba 4. Ano uznávam ze prvy test sa môže zdať chybný keďže je to v podstate dvoj-chyba co by nemalo byť.
